# Generated by Django 6.0.3 on 2026-03-30 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='data_fim_recorrencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data fim da recorrencia'),
        ),
        migrations.CreateModel(
            name='TransacaoExcecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data excluida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecoes', to='finance.transacao', verbose_name='Transacao')),
            ],
            options={
                'verbose_name': 'Excecao de transacao',
                'verbose_name_plural': 'Excecoes de transacoes',
                'ordering': ['data'],
                'unique_together': {('transacao', 'data')},
            },
        ),
    ]
